<a href="https://colab.research.google.com/github/sobiyeo/iExcel/blob/main/Hamoye%20Notes%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [4]:
a.shape

(2, 5)

In [5]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# New Section

Accessing Array items

In [6]:
a[0]

array([1, 2, 3, 4, 5])

In [7]:
a[1]

array([ 6,  7,  8,  9, 10])

Multi indexing, Row and item

In [8]:
a[0,4]

5

In [9]:
a[1,3]

9

Array slicing

In [10]:
a[0][:3]

array([1, 2, 3])

In [11]:
a[1][:4]

array([6, 7, 8, 9])

In [12]:
a.dtype

dtype('int64')

***Note***: In order to change integers to strings or work with strings value in numpy. we add the "dtype = 'S'" to the end of the array

In [15]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype = 'S')


In [16]:
c

array([[b'1', b'2', b'3', b'4', b'5'],
       [b'6', b'7', b'8', b'9', b'10']], dtype='|S2')

In [17]:
c.shape

(2, 5)

In [18]:
c.dtype

dtype('S2')

**Reshaping** **an** **array**

In [20]:
f = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [21]:
g = f.reshape(4,3)

In [22]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Reshaping into 3D array

In [24]:
i = np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [25]:
u = i.reshape(2,3,2)

In [26]:
u

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])