<a href="https://colab.research.google.com/github/sobiyeo/iExcel/blob/main/HamoyeClass_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
scores = [400, 200, 600, 800]
V = pd.Series(scores)

In [ ]:
s = np.array([400, 200, 600, 800])


In [ ]:
s

array([400, 200, 600, 800])

In [ ]:
print(V)

0    400
1    200
2    600
3    800
dtype: int64


**Note**; while numpy will provide the data as an array, pandas will give in tabular form

CHANGING INDEXING
Pandas allows for renaming index of list other than the default 0 1 2 3 etc.

In [ ]:
scores = [400, 200, 600, 800]
myS = pd.Series(scores, index = ["math", "eng", "fre","sos"])

In [ ]:
print (myS)

math    400
eng     200
fre     600
sos     800
dtype: int64


In [ ]:
myS["math"]

400

A SERIES AS A DICTIONARY

In [ ]:
calories = {"day1":420, "day2":300, "day3":390}
myvar = pd.Series(calories)
print(myvar)

day1    420
day2    300
day3    390
dtype: int64


For dictionaries, a dictionaries' key already serves as the index. its therefore not necessary to specify index anymore

In [ ]:
myvar["day1"]

420

getting values in pandas

In [ ]:
myvar.values

array([420, 300, 390])

getting values in numpy

In [ ]:
s

array([400, 200, 600, 800])

**DATA** **FRAMES** **IN** **PANDAS**

Datframes in Pandas is like multidimensional data arrays (2d,3d) in numpy

In [ ]:
scores = [400, 200, 600, 800]
Dt = pd.DataFrame(scores)

In [ ]:
print(Dt)

     0
0  400
1  200
2  600
3  800


To specify the heading of the column instead of the default 0

In [ ]:
Dt = pd.DataFrame((scores), columns = ["numbers"])


In [ ]:
print (Dt)

   numbers
0      400
1      200
2      600
3      800


In [ ]:
pd.DataFrame({
    "Numbers": [1,2,3,4,5],
    "Sq. Nums": [1,4,9,16,25]})

Numbers  Sq. Nums
0        1         1
1        2         4
2        3         9
3        4        16
4        5        25

one of the great ways to work with column indexing in pandas is using a dictionary.

df is the most popular way of naming dataframes.

In [ ]:
df = pd.DataFrame({
   "Numbers": [1,2,3,4,5],
    "Sq. Nums": [1,4,9,16,25]})

In [ ]:
df.loc[1]

Numbers     2
Sq. Nums    4
Name: 1, dtype: int64

Using Pandas for a numpy array

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [ ]:
df2 = pd.DataFrame(arr.T, columns =["no", "mm"])

Please, I used the "arr.t (Transpose) because the array as initially shaped as a 2x5 instead of a 5x2

In [ ]:
df2

no  mm
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [ ]:
!wget.https://gist.github.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a

/bin/bash: line 1: wget.https://gist.github.com/Thanatoz-1/9e7fdfb8189f0cdf5d73a494e4a6392a: No such file or directory


In [ ]:
data = pd.read_csv("Iris Dataset.csv")

In [ ]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 5 columns]

In [ ]:
data.shape

(150, 5)

data.head - first 5 rows
data.tail.= - last 5 rows

In [ ]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

        target  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

Checking for null values

In [ ]:
data.isna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                False             False              False             False   
1                False             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False             False   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False              False             False   

     target  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
145   False  
146   False  
147   False  
148   False  
149   False  

[150 rows x 5 columns]

In [ ]:
data.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

Unlike numpy, pandas allows a combination of various data type in a single array

To include all the description and

In [ ]:
subdf = data.describe(include = "all")

In [ ]:
subdf.isna().sum()

sepal length (cm)    3
sepal width (cm)     3
petal length (cm)    3
petal width (cm)     3
target               7
dtype: int64

DATA CLEANING

In [ ]:
subdf.dropna()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count              150.0             150.0              150.0   

       petal width (cm) target  
count             150.0    150

To drop selected columns

In [ ]:
subdf2 = subdf.drop(["target"], axis = 1)

In [ ]:
subdf2.isna().sum()

sepal length (cm)    3
sepal width (cm)     3
petal length (cm)    3
petal width (cm)     3
dtype: int64

In [ ]:
subdf2.dropna()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.198667  
std            0.763161  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

To check for duplicates

In [ ]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [ ]:
data.duplicated().any()

True