<a href="https://colab.research.google.com/github/sobiyeo/iExcel/blob/main/Hamoye1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
a.shape

(2, 5)

In [ ]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# New Section

Accessing Array items

In [ ]:
a[0]

array([1, 2, 3, 4, 5])

In [ ]:
a[1]

array([ 6,  7,  8,  9, 10])

Multi indexing, Row and item

In [ ]:
a[0,4]

5

In [ ]:
a[1,3]

9

Array slicing

In [ ]:
a[0][:3]

array([1, 2, 3])

In [ ]:
a[1][:4]

array([6, 7, 8, 9])

In [ ]:
a.dtype

dtype('int64')

***Note***: In order to change integers to strings or work with strings value in numpy. we add the "dtype = 'S'" to the end of the array

In [ ]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype = 'S')


In [ ]:
c

array([[b'1', b'2', b'3', b'4', b'5'],
       [b'6', b'7', b'8', b'9', b'10']], dtype='|S2')

In [ ]:
c.shape

(2, 5)

In [ ]:
c.dtype

dtype('S2')

**Reshaping** **an** **array**

In [ ]:
f = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
g = f.reshape(4,3)

In [ ]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Reshaping into 3D array

In [ ]:
i = np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [ ]:
u = i.reshape(2,3,)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Using Numpy.Random funtion

In [30]:
np.random.randint(50)

40

To create ramdom array in numpy

In [33]:
np.random.randint(100, size = 5)

array([61,  7, 79, 81,  8])

In [34]:
np.random.randint(100, size =(3, 4) )


array([[52, 39, 81, 10],
       [57, 98, 35, 80],
       [ 5, 27, 92, 76]])

In [35]:
np.random.randint(100, size = (3,4,2))


array([[[ 5, 41],
        [51, 26],
        [68,  9],
        [76, 41]],

       [[96, 30],
        [37, 56],
        [62, 65],
        [82, 48]],

       [[28, 93],
        [28, 14],
        [ 3, 67],
        [ 7, 75]]])

However in the case of float or decimsls the size brackets in unneeded

In [37]:
np.random.rand(5,2)


array([[0.92584234, 0.87813844],
       [0.93720896, 0.63476179],
       [0.86836829, 0.59595705],
       [0.33014516, 0.54620964],
       [0.52371219, 0.17927095]])

Random binomial distribution

In [39]:
np.random.binomial(n=5, p=0.5, size =10)

array([2, 4, 2, 2, 3, 1, 1, 2, 1, 0])

where n is no of range wherein items can come, p is probability value and size is the lenght of array

Matrix operation with numpy

In [41]:
m = np.array([[1,5,8,9,10], [2,3,4,8,9]])

In [42]:
o = np.array ([[8,9,10,11,7], [7,18,19,18,22]])

In [43]:
m.shape
o.shape

(2, 5)

In [44]:
m*o

array([[  8,  45,  80,  99,  70],
       [ 14,  54,  76, 144, 198]])

In [45]:
m+o

array([[ 9, 14, 18, 20, 17],
       [ 9, 21, 23, 26, 31]])